### ISSUE TITLE
Suggestion in prison

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-spawn#16]
When a player enters the server, he carries a value injail
That disappears the list of areas that will spawn
And only spawn gets him in prison only and hidden other
hide this   
 ["legion"] = 
    ["policedp"] = 
    ["paleto"] = 
    ["motel"] = 
and show this only
    ["prison"] =

**Comment by SamShanks1** [comment]
If you try spawn in any of those it will force you back into prison
