### ISSUE TITLE
How to add more spawn locations

### ISSUE THREAD

**Issue by GBSpeedyRP** [qbcore-framework/qb-spawn#19]
I wanted to add some more spawn locations round the map i have tried bit it shows in the login screen when I click it nothing happens.

**Comment by ihyajb** [comment]
you just add it to the config with the name and the cords

```
["island"] = {
        coords = vector4(4515.46, -4529.23, 4.12, 16.84),
        location = "island",
        label = "Starter Island",
    },
```
