### ISSUE TITLE
[SUGGESTION] Spawn at Apartment Script

### ISSUE THREAD

**Issue by justkryptic** [qbcore-framework/qb-spawn#21]
Hello, I am currently setting up my own server. With the base script, players are able to spawn at their houses locations and last location. What I am looking for is an edited script in the Client Lua, around lines 42-68 that allows a player to ALSO select the apartment they got when creating their character.

I am somewhat new to developing, but have a general idea on how to make the script. I have tried, but haven't been able to make it functional yet.

I am not sure where to post this for help, so I am using the request tab to do so. If anyone can whip this script up in a timely manner (considering it's not that many changes to the base script) I will pay for it.

For any questions or comments feel free to reach out on discord JustKryptic#4307

**Comment by justkryptic** [comment]
In the client lua, I believe this is the section that needs editing (line38):

RegisterNetEvent('qb-spawn:client:setupSpawns', function(cData, new, apps)
    if not new then
        QBCore.Functions.TriggerCallback('qb-spawn:server:getOwnedHouses', function(houses)
            local myHouses = {}
            if houses ~= nil then
                for i = 1, (#houses), 1 do
                    table.insert(myHouses, {
                        house = houses[i].house,
                        label = Config.Houses[houses[i].house].adress,
                    })
                end
            end

            Citizen.Wait(500)
            SendNUIMessage({
                action = "setupLocations",
                locations = QB.Spawns,
                houses = myHouses,
            })
        end, cData.citizenid)
    elseif new then
        SendNUIMessage({
            action = "setupAppartements",
            locations = apps,
        })
    end
end)

**Comment by Rhydium** [comment]
Any update on whether this will be implemented or not? I think it would be a very good addition.

**Comment by Rhydium** [comment]
Closed without any reaction, would this still be possible?
