### ISSUE TITLE
SPAWN FOREVER LOADING

### ISSUE THREAD

**Issue by Iamozzyy** [qbcore-framework/qb-spawn#25]
When joining the server everything seems normal, no errors in consoles etc. When creating a character on qb-multicharacter
 and then press continue the qb-spawn forever loads with a black screen and spinning circle in bottom right and never passes, even when relogging or restarting the server. Not sure what is causing this issue but only has started when ive recently upgraded to the newer versions of QB.

**Comment by ShaAlexander** [comment]
Same here need to create an new character now and swop its bsn
