### ISSUE TITLE
Issue Report - Help

### ISSUE THREAD

**Issue by Falsire** [qbcore-framework/qb-spawn#28]
I am trying to create a new spawn for Mount Zonah hospital, but when I load into the server the spawn select is broken. What else do I need to change for this to work? What does it mean by the name must be unique for the spawn? Kinda confused. 

This part confuses me the most - 

  ["spawn1"] = { -- Needs to be unique
  location = "spawn1", -- Needs to be unique
  
  How do I fix this? 

 ["mountzh"] = {
        coords = vector4(-463.03, -338.82, 34.5, 82.23),
        location = "mountzh"
        label = "Mount Zonah",
    },
}

**Comment by Suranos** [comment]
Make sure you maintained the structure of the QB.Spawns table

`QB.Spawns = {
    ["legion"] = {
        coords = vector4(195.17, -933.77, 29.7, 144.5),
        location = "legion",
        label = "Legion Square",
    },

    ["policedp"] = {
        coords = vector4(428.23, -984.28, 29.76, 3.5),
        location = "policedp",
        label = "Police Department",
    },

    ["paleto"] = {
        coords = vector4(80.35, 6424.12, 31.67, 45.5),
        location = "paleto",
        label = "Paleto Bay",
    },

    ["mountzh"] = {
        coords = vector4(-463.03, -338.82, 34.5, 82.23),
        location = "mountzh",
        label = "Mt. Zonah Hospital",
    },

    ["motel"] = {
        coords = vector4(327.56, -205.08, 53.08, 163.5),
        location = "motel",
        label = "Motels",
    },
}`

This is the QB.Spawns with the Hospital added

**Comment by Falsire** [comment]
See that is what I added, but it didn't work. I'll check that out
