### ISSUE TITLE
Spawn Error

### ISSUE THREAD

**Issue by pedroalmeida91** [qbcore-framework/qb-spawn#33]
Error joining server

**Screenshots**
![image](https://user-images.githubusercontent.com/97103637/155232444-2612561b-5e99-440e-a530-b8de3b762c63.png)

**Comment by Hex2319** [comment]
I'm having this error now as well. did you figure out what the issue was?

**Comment by Salzian** [comment]
What's the reason for closing this issue @GhzGarage ? We had this issue recently and had to build a hacky workaround. Has the issue been resolved in latest master?
