### ISSUE TITLE
[BUG] qb-spawn error

### ISSUE THREAD

**Issue by OuterRealm2000** [qbcore-framework/qb-spawn#34]
**Describe the bug**
Currently, experiencing loss of location selection of selecting a character. Just get a spinning wheel of loading death with a black screen.  Although, oddly enough if I press keys like "L" or wait a while I still get a paycheck or it will tell me I dont have keys for this vehicle.

**To Reproduce**
1. Go to any custom MLO
2. Go inside and then stop the mlo in resources 
3. Client will crash but character will not exit the game 
4. Use admin account to kick user
5. Then F8 quit and reload
6. Select the character used 
7. TADA spinning wheel of death

Things I noticed will looking into this issue.  
1. My qb-spawn is unedited I even reinstalled from the most recent github same issue always line #39 as seen in the included image.
2. the MySQL database keeps updating the location for my character to the same coords  
 {"x":-812.5977783203125,"y":182.14944458007813,"z":75.920166015625}
 

**Expected behavior**
The ability to restart the server and select last login.

**Screenshots**
![image](https://user-images.githubusercontent.com/89769391/155314335-e4bff9d0-3c4b-4721-bfb3-8b100cddb3cb.png)

**Questions (please complete the following information):**
 - When you last updated: qb-spawn like I said I reinstalled it tonight
 - Are you using custom resource? which ones? 
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by ihyajb** [comment]
that means either your qb-spawn, qb-apartments, or qb-houses is messed up. As spawn is dependent on those scripts

**Comment by flyinggoatman** [comment]
How would you resolve this issue? Could you do something to make the user spawn again without restoring a backup?

**Comment by flyinggoatman** [comment]
> that means either your qb-spawn, qb-apartments, or qb-houses is messed up. As spawn is dependent on those scripts
How would you resolve this issue? Could you do something to make the user spawn again without restoring a backup?

**Comment by itismejoey** [comment]
This still appears to be an issue. I did a fresh install of the three resources that were mentioned above. While not often, this error is still appearing for players joining our server. It's also not as easy as a quick restart, as it may continue to happen several times. This is also mentioned in #33, but also closed without a real fix.

**Comment by ChlxeThomson** [comment]
This has happened to me and it so annoying
