### ISSUE TITLE
[SUGGESTION] qb-spawn based on jobs

### ISSUE THREAD

**Issue by WardDevs** [qbcore-framework/qb-spawn#36]
**Describe the feature you'd like**
you could spawn based on jobs like when your job is police you could see the police department thingy to spawn but if you are unemployed you cant see the police department to spawn and you could also manage it on config.lua i think it would be a nice touch to it

    ["policedp"] = {
        coords = vector4(428.23, -984.28, 29.76, 3.5),
        location = "policedp",
        label = "Police Department",
        job = "police",
    },

**Comment by IdrisDose** [comment]
**CONSIDERED**

**Comment by ShortKeeper** [comment]
could also do a similar way and have gang related spawns as well, and are either of these a things yet?
