### ISSUE TITLE
[SUGGESTION] Auto spawn last location

### ISSUE THREAD

**Issue by Marttins011** [qbcore-framework/qb-spawn#39]
Add Config option to be possible spawn automatic at last location without menu to select

**Comment by IdrisDose** [comment]
**CONSIDERED**

**Comment by deekay-au** [comment]
I too would love to see this

**Comment by cosmo131** [comment]
An additional function that you spawn only on the last position I would like to welcome.

**Comment by Xiantyl** [comment]
Would like this feature as well

**Comment by xxUnknown13xx** [comment]
I agree with this. I've been trying to have this option 😅
I just auto spawn the last location I was at and not click where I wanna be at.

**Comment by Khatrie** [comment]
just gonna +1 this, hoping we get this feature.

**Comment by Scones91** [comment]
+1 on this!

**Comment by am3nd01m** [comment]
+1!

**Comment by W0lfZ1** [comment]
Hello i'm new here how can i config with automatic last location?

**Comment by TommyAshh** [comment]
Any update on this? I’m wanting the same thing

**Comment by gnika** [comment]
same here !
how could we do that ?

**Comment by Kimarauskas** [comment]
Is it possible to make today?

**Comment by L0wic21** [comment]
We really need this

**Comment by Im-Your-Papi** [comment]
> We really need this

https://discordapp.com/channels/831626422232678481/1056916131530682448/1056916131530682448

**Comment by Im-Your-Papi** [comment]
> Is it possible to make today?

https://discordapp.com/channels/831626422232678481/1056916131530682448/1056916131530682448

**Comment by Im-Your-Papi** [comment]
> same here ! how could we do that ?

https://discordapp.com/channels/831626422232678481/1056916131530682448/1056916131530682448

**Comment by Im-Your-Papi** [comment]
> Any update on this? I’m wanting the same thing

https://discordapp.com/channels/831626422232678481/1056916131530682448/1056916131530682448

**Comment by L0wic21** [comment]
> > We really need this
> 
> https://discordapp.com/channels/831626422232678481/1056916131530682448/1056916131530682448

I dont know what you sent but it does not work

**Comment by Im-Your-Papi** [comment]
> > > We really need this
> > 
> > 
> > https://discordapp.com/channels/831626422232678481/1056916131530682448/1056916131530682448
> 
> I dont know what you sent but it does not work

oh sorry, here you go----

**_This modification allows you to only spawn at the last location, no menu to choose a location will pop up._**

**qb-multicharacter/html/index.html#325
Replace line with this one:**

axios.post('https://qb-multicharacter/spawnLastLocation', {


**qb-multicharacter/client/main.lua
Add:**

RegisterNUICallback('spawnLastLocation', function(data, cb)
    DoScreenFadeOut(10)
    local cData = data.cData
    SetEntityAsMissionEntity(charPed, true, true)
    DeleteEntity(charPed)
    TriggerServerEvent('qb-multicharacter:server:spawnLastLocation', cData)

    SetNuiFocus(false, false)
    skyCam(false)

    cb("ok")
end)

RegisterNetEvent('qb-multicharacter:client:spawnLastLocation', function(coords)
    local ped = PlayerPedId()
    SetEntityCoords(ped, coords.x, coords.y, coords.z)
    SetEntityHeading(ped, coords.w)
    FreezeEntityPosition(ped, false)
    SetEntityVisible(ped, true)
    TriggerServerEvent('QBCore:Server:OnPlayerLoaded')
    TriggerEvent('QBCore:Client:OnPlayerLoaded')
    DoScreenFadeIn(250)
end)



**qb-multicharacter/server/main.lua
Add:**

RegisterNetEvent('qb-multicharacter:server:spawnLastLocation', function(cData)
    local src = source
    if QBCore.Player.Login(src, cData.citizenid) then
        repeat
            Wait(10)
        until hasDonePreloading[src]
        print('^2[qb-core]^7 '..GetPlayerName(src)..' (Citizen ID: '..cData.citizenid..') has succesfully loaded!')
        QBCore.Commands.Refresh(src)
        loadHouseData(src)
        local coords = json.decode(cData.position)
        TriggerClientEvent('qb-multicharacter:client:spawnLastLocation', src, coords)
    end
end)

**Comment by L0wic21** [comment]
> 

First of all, thank you so much for this, it is trully amazing.
Second, I im trying to make this work with bb-multichar, but it dosent work. I already fixed mnay errors, but now im stuck

This is my error
![image](https://github.com/qbcore-framework/qb-spawn/assets/123094149/81a9bf48-5572-4fc7-9012-39827ce471f1)

This is the origin
`RegisterNetEvent('bb-multichar:client:spawnLastLocation', function(coords)
local ped = PlayerPedId()
SetEntityCoords(ped, coords.x, coords.y, coords.z)
SetEntityHeading(ped, coords.w)
FreezeEntityPosition(ped, false)
SetEntityVisible(ped, true)
TriggerServerEvent('QBCore:Server:OnPlayerLoaded')
TriggerEvent('QBCore:Client:OnPlayerLoaded')
DoScreenFadeIn(250)
end)`

This is where it is called
`RegisterNetEvent('bb-multichar:server:spawnLastLocation', function(cData)
  local src = source
  if QBCore.Player.Login(src, cData.citizenid) then
    repeat
    Wait(10)
    until hasDonePreloading[src]
    print('^2[qb-core]^7 '..GetPlayerName(src)..' has succesfully loaded!')
    QBCore.Commands.Refresh(src)
    loadHouseData(src)
    local coords = json.decode(cData.position)
    TriggerClientEvent('bb-multichar:client:spawnLastLocation', src, coords)
  end
end)`

And this is where That one above is called
`RegisterNUICallback('spawnLastLocation', function(data, cb)
DoScreenFadeOut(10)
local cData = data.cData
SetEntityAsMissionEntity(charPed, true, true)
DeleteEntity(charPed)
TriggerServerEvent('bb-multichar:server:spawnLastLocation', data.citizenid)
SetNuiFocus(false, false)
skyCam(false)
cb("ok")
end)`

I Think the error might be coming from line `TriggerServerEvent('bb-multichar:server:spawnLastLocation', data.citizenid)`
As i modified your original "cData" so that it takes the data provided by bb-multichar
Here is where it is called `$.post("https://bb-multichar/spawnLastLocation", JSON.stringify({ citizenid: $(`.container #slider #selectcharacter[data-char='${char}']`).attr('data-citizenid')}));`
I Have two possible way of fdoing this, either I change the JS so that it give cData, or I modify the `[client](client:spawnLastLocation)` so that it works with the data provided by the JS code.

Now I have no idea if this is even possible, im not an expert in lua nor JavaScript, but if you think of something, it would mean the world

**Comment by Dzendoy** [comment]
> > > > We really need this
> > > 
> > > 
> > > https://discordapp.com/channels/831626422232678481/1056916131530682448/1056916131530682448
> > 
> > 
> > I dont know what you sent but it does not work
> 
> oh sorry, here you go----
> 
> **_This modification allows you to only spawn at the last location, no menu to choose a location will pop up._**
> 
> **qb-multicharacter/html/index.html#325 Replace line with this one:**
> 
> axios.post('https://qb-multicharacter/spawnLastLocation', {
> 
> **qb-multicharacter/client/main.lua Add:**
> 
> RegisterNUICallback('spawnLastLocation', function(data, cb) DoScreenFadeOut(10) local cData = data.cData SetEntityAsMissionEntity(charPed, true, true) DeleteEntity(charPed) TriggerServerEvent('qb-multicharacter:server:spawnLastLocation', cData)
> 
> ```
> SetNuiFocus(false, false)
> skyCam(false)
> 
> cb("ok")
> ```
> 
> end)
> 
> RegisterNetEvent('qb-multicharacter:client:spawnLastLocation', function(coords) local ped = PlayerPedId() SetEntityCoords(ped, coords.x, coords.y, coords.z) SetEntityHeading(ped, coords.w) FreezeEntityPosition(ped, false) SetEntityVisible(ped, true) TriggerServerEvent('QBCore:Server:OnPlayerLoaded') TriggerEvent('QBCore:Client:OnPlayerLoaded') DoScreenFadeIn(250) end)
> 
> **qb-multicharacter/server/main.lua Add:**
> 
> RegisterNetEvent('qb-multicharacter:server:spawnLastLocation', function(cData) local src = source if QBCore.Player.Login(src, cData.citizenid) then repeat Wait(10) until hasDonePreloading[src] print('^2[qb-core]^7 '..GetPlayerName(src)..' (Citizen ID: '..cData.citizenid..') has succesfully loaded!') QBCore.Commands.Refresh(src) loadHouseData(src) local coords = json.decode(cData.position) TriggerClientEvent('qb-multicharacter:client:spawnLastLocation', src, coords) end end)

Can someone provide the link for axios post? I really need this so if anyone could help I would be greatful.

**Comment by kaynegraham** [comment]
`<script src="https://cdn.jsdelivr.net/npm/axios@1.4.0/dist/axios.min.js"></script>`
put this in your html file

**Comment by Dzendoy** [comment]
> `<script src="https://cdn.jsdelivr.net/npm/axios@1.4.0/dist/axios.min.js"></script>` put this in your html file

im sorry i must be dumb but where in html do i put this?

**Comment by kaynegraham** [comment]
in <head>

**Comment by kaynegraham** [comment]
`<head>`

**Comment by Dzendoy** [comment]
like this? 
![image](https://github.com/qbcore-framework/qb-spawn/assets/156862358/c6f07874-33b3-4e30-acf5-a9af980fe9de)

**Comment by Dzendoy** [comment]
oh nwm i see it thxx

**Comment by Psycho66626** [comment]
> > > > We really need this
> > > 
> > > 
> > > https://discordapp.com/channels/831626422232678481/1056916131530682448/1056916131530682448
> > 
> > 
> > I dont know what you sent but it does not work
> 
> oh sorry, here you go----
> 
> **_This modification allows you to only spawn at the last location, no menu to choose a location will pop up._**
> 
> **qb-multicharacter/html/index.html#325 Replace line with this one:**
> 
> axios.post('https://qb-multicharacter/spawnLastLocation', {
> 
> **qb-multicharacter/client/main.lua Add:**
> 
> RegisterNUICallback('spawnLastLocation', function(data, cb) DoScreenFadeOut(10) local cData = data.cData SetEntityAsMissionEntity(charPed, true, true) DeleteEntity(charPed) TriggerServerEvent('qb-multicharacter:server:spawnLastLocation', cData)
> 
> ```
> SetNuiFocus(false, false)
> skyCam(false)
> 
> cb("ok")
> ```
> 
> end)
> 
> RegisterNetEvent('qb-multicharacter:client:spawnLastLocation', function(coords) local ped = PlayerPedId() SetEntityCoords(ped, coords.x, coords.y, coords.z) SetEntityHeading(ped, coords.w) FreezeEntityPosition(ped, false) SetEntityVisible(ped, true) TriggerServerEvent('QBCore:Server:OnPlayerLoaded') TriggerEvent('QBCore:Client:OnPlayerLoaded') DoScreenFadeIn(250) end)
> 
> **qb-multicharacter/server/main.lua Add:**
> 
> RegisterNetEvent('qb-multicharacter:server:spawnLastLocation', function(cData) local src = source if QBCore.Player.Login(src, cData.citizenid) then repeat Wait(10) until hasDonePreloading[src] print('^2[qb-core]^7 '..GetPlayerName(src)..' (Citizen ID: '..cData.citizenid..') has succesfully loaded!') QBCore.Commands.Refresh(src) loadHouseData(src) local coords = json.decode(cData.position) TriggerClientEvent('qb-multicharacter:client:spawnLastLocation', src, coords) end end)

It works on me, thank you so much!!!! only 1 who decided it.
