### ISSUE TITLE
[SUGGESTION] Spawn in owned apartment

### ISSUE THREAD

**Issue by Kuwuz** [qbcore-framework/qb-spawn#42]
I am unable to spawn on the apartment in which i have been given in game, it just shows the standard of police department, paleto, motels and legion im also not receiving any errors with this

**Comment by Molicheu** [comment]
You're not receiving any errors because there isn't anything wrong happening. It's made for you to spawn on your owned houses not owned apartments

**Comment by CentralstationenRP** [comment]
I would love to have so we can spawn at apartment to. make more sense

**Comment by Rhydium** [comment]
Any update on this? :)

**Comment by Smokiiee** [comment]
Would love to have this
