### ISSUE TITLE
[BUG] qb-spawn.sql missing

### ISSUE THREAD

**Issue by DooubleTap** [qbcore-framework/qb-spawn#43]
**Describe the bug**
the file qb-spawn.sql is missing from this repo.

**Comment by DooubleTap** [comment]
am i blind or its missing?

**Comment by BerkieBb** [comment]
It doesn't exist

**Comment by DooubleTap** [comment]
ok then, why would it say ''import the qb-spawn.sql'' but it does not exist... it makes no sens...

**Comment by BerkieBb** [comment]
If you read the latest commit, you would know why
