### ISSUE TITLE
[SUGGESTION] Force spawn last location when in prison

### ISSUE THREAD

**Issue by SPKReality** [qbcore-framework/qb-spawn#46]
**Is your feature request related to a problem? Please describe.**
When someone is in prison and they log in and out they can choose somewhere else to spawn and it doesnt put them back into prison

-----

**Describe the feature you'd like**
When the player loads back into the server it should spawn them back in prison and make them finish the rest of there time.

------

**Describe alternatives you've considered**
I think its a good idea as it stops  players combat logging to get out of prison and when people accidentally spawn somewhere else and then lose there items

-----

**Additional context**
Im pretty sure someone else has already suggested this and imnot sure if its been added or not but any way im just gonna make another suggestion for it just incase. also i am not sure if some of the things ive said have been fixed / added so please forgive me if its already been done!

**Comment by nzkfc** [comment]
This is what I came to post, we really need this.
