### ISSUE TITLE
Issue with spawning in! Client.lua line 201

### ISSUE THREAD

**Issue by GLaZeD-DoHNuTz** [qbcore-framework/qb-spawn#5]
Greetings,

This issue was after I created a character already in the previous day or so.

After installing this resource, I was not able to fully spawn in. I only saw a black screen while the loading bar at the bottom right was spinning. I checked the log and it mentioned that line 201 in client.lua had an invalid key: h

After playing around with the code, I finally found a workaround. So instead of:

SetEntityHeading (ped, pos.h)

I did this instead and it worked:
SetEntityHeading (ped, 195.17, -933.77, 29.7, 144.5)

I just threw in the Legions Squares coordinates and I was able to spawn in!

I even tried selecting a different spawn point to see if it would push me back to Legions Square, but it spawned me in the location I selected.

**Comment by GLaZeD-DoHNuTz** [comment]
I also cleared the cache within the mod files to ensure it won't maintain the old code.

**Comment by GhzGarage** [comment]
I just did a fresh install about 1 hour ago and don't have any of those issues so i'm not sure

**Comment by steelkodi** [comment]
Im having the same issue as well

**Comment by GhzGarage** [comment]
Could not replicate

**Comment by GLaZeD-DoHNuTz** [comment]
@steelkodi If you are using the Qbcore framework, you have to change line 201

SetEntityHeading (ped, pos.h)

TO

**SetEntityHeading (ped, pos.w)**


Below is the reference:

QBCore.Functions.GetCoords = function(entity)
    local coords = GetEntityCoords(entity, false)
    local heading = GetEntityHeading(entity)
    return {
        x = coords.x,
        y = coords.y,
        z = coords.z,
        **w = heading**
