### ISSUE TITLE
[SUGGESTION]Can we have the vue files?

### ISSUE THREAD

**Issue by SuperMan-Sam** [qbcore-framework/qb-spawn#50]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the feature you'd like**
A clear and concise description of what you want to happen. and with as much detail as possible how it would function in your opinion. Please try to keep it unique.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered for people to have in mind just in case the main idea isn't liked but a derivative is.

**Additional context**
Just want to edit vue.js

**Comment by Z3rio** [comment]
There are no "vue files". The files that you already have are the source files.
It uses Vue 2.0 CDN.
