### ISSUE TITLE
[BUG] Stuck in clouds after pressing "confirm"

### ISSUE THREAD

**Issue by Veolene** [qbcore-framework/qb-spawn#53]
**Describe the bug**

Seems like there is a problem with someone in my server attempting to post to the Nui. It seems he can press the buttons, and this error shows up. After pressing confirm the gets stuck in the clouds with the menu gone.

**To Reproduce**
1. connect to the server
2. choose your character
3. press one of the spawn locations to get the error
4. press confirm for the menu to disappear and for yourself to be stuck in the clouds

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/1028111940469407766/1028112048573382656/unknown.png)

**Questions (please complete the following information):**
 When you last updated: [e.g. last week]
 - yesterday
 Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - clean qbcore
 Have you renamed `qb-` to something custom? [e.g. yes/no]
 - no

**Comment by nzkfc** [comment]
Double check your player citizen ID, sometimes for whatever reason the players citizen ID is lowercase, or someone accidently edited it in DB by mistake.
