### ISSUE TITLE
[SUGGESTION] We Need Vue Source Code

### ISSUE THREAD

**Issue by PT-Mohamed-Hussein** [qbcore-framework/qb-spawn#55]
**Is your feature request related to a problem? Please describe.**
Yes, There Is No Zoom When WE Choose Apartment Or When WE Try To Choose Last Spawn I Think You Forget To Make The Fetch Request To Move The Cam

**Describe the feature you'd like**
Just The Vue Source Code For The HTML, Css, Js

**Describe alternatives you've considered**
Fix The Zoom Issue

**Additional context**
...

**Comment by Z3rio** [comment]
There are no "vue files". The files that you already have are the source files.
It uses Vue 2.0 CDN.
