### ISSUE TITLE
 error during NUI callback chooseAppa: @qb-spawn/client.lua:136: attempt to index a nil value (global 'Apartments')

### ISSUE THREAD

**Issue by Senpainick** [qbcore-framework/qb-spawn#71]
**Describe the bug**
 error during NUI callback chooseAppa: @qb-spawn/client.lua:136: attempt to index a nil value (global 'Apartments')

**To Reproduce**
1. Go to loading screen '...'
2. Click on character  '....'
3 see black screen error 

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**
Stuck in black screen replaced qb-spawn , multi-character,

**Comment by Senpainick** [comment]
anyone?

**Comment by YG0007** [comment]
Make sure your are using qb-apartments

**Comment by Jesolok** [comment]
did anyone find a fix?
