### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sk3tch725** [qbcore-framework/qb-spawn#74]
**Describe the bug**
I have an issue where no matter what spawn i select including last location i always spawn legion square. 

**To Reproduce**
1. Go in Game.
2. Click on any of the locations in the list.
3. Select areas to spawn, defaults to legion square, even removed it from the list. 
4. happens every single time. 

**Expected behavior**
To spawn on the selected area of my choosing. 

**Screenshots**

**Questions (please complete the following information):**
 - Most Recent Build from TX install.
 - Are you using custom resource? Just QB-Spawn
 - Have you renamed `qb-` to something custom? No.

**Additional context**

**Comment by ChristianBDev** [comment]
@Sk3tch725 

Do you have the latest qb-spawn? If not, when was it last updated? 
Is this a custom script you downloaded somewhere or here? 
What Tx-Build (artifacts) do you have?

**Comment by ChristianBDev** [comment]
@Sk3tch725 have you tried PR #72?

**Comment by ryan11444** [comment]
I have this same issue. Has anyone found a fix for this? I have the latest version of qb-spawn. For some reason if I use my apartment to logout to character selection screen, then if I pick a character and choose a spawn, the spawn points work...but otherwise, it always spawns at legion no matter what location I pick.

**Comment by kaynegraham** [comment]
@ryan11444 Are you still having this issue?

**Comment by ryan11444** [comment]
Yes

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 12, 2024 at 8:59 PM, ***@***.***> wrote:   


@ryan11444 Are you still having this issue?

**Comment by kaynegraham** [comment]
@ryan11444 please download the latest version and let me know how it goes

**Comment by kaynegraham** [comment]
@ryan11444 ?

**Comment by ryan11444** [comment]
Yeah, still have the issue. Was thinking about buying a new spawn selector script instead of using the default qbcore to see if that fixes it.

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 15, 2024 at 10:39 PM, ***@***.***> wrote:   


@ryan11444 ?

**Comment by kaynegraham** [comment]
okay, are you on the latest game build, qb-spawn & qb-core?

**Comment by ryan11444** [comment]
Yep, everything is up to date. No clue what's causing it. If players /logout after joining and choose their character again, it will work properly. Otherwise, it always spawns them at Legion no matter what anyone picks.

    On Tuesday, January 16, 2024 at 09:57:52 PM CST, Kayne ***@***.***> wrote:  
 
 


okay, are you on the latest game build, qb-spawn & qb-core?

**Comment by kaynegraham** [comment]
okay, try & remove legion from the code & see what happens then.

**Comment by alirezagood** [comment]
i had the same issue.
fixed by disabling qb-community-service or you can fix the code or replace it with another one

**Comment by TKDubsta1101** [comment]
This is a bug with qb-community-service, please file the bug report there
